config/routes.rb
Featuremgmt::Application.routes.draw do
  root :to => "ideas#index"
  resources :ideas do
    resources :comments
    member do
      get 'upvote'
      post 'select_tag'
      post 'deselect_tag'
    end
  end
  resources :tags
  resources :idea_tags
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :revenue_opp, :text, :idea_id
  belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :description, :name, :votes
  has_many :comments, :dependent => :destroy
  has_many :idea_tags
  has_many :tags, :through => :idea_tags
end

app/models/idea_tag.rb
class IdeaTag < ActiveRecord::Base
  # attr_accessible :idea_id, :tag_id
  belongs_to :idea
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :idea_tags
  has_many :ideas, :through => :idea_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @idea = Idea.find(params[:idea_id])
    @comments = Comment.find_all_by_idea_id(@idea.id)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end
  
  def new
    @idea = Idea.find(params[:idea_id])
    @comment = Comment.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end
  
  def show
    @idea = Idea.find(params[:idea_id])
    @comment = Comment.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end
  
  def create
    idea = Idea.find(params[:idea_id])
    @comment = Comment.new(params[:comment])
    @comment.idea = idea #associates the comment with the right idea
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to idea, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @comment = Comment.find(params[:id])
    
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
        
end

app/controllers/idea_tags_controller.rb
class IdeaTagsController < ApplicationController
  def index
    @ideatags = IdeaTag.all
  end
  
  def create
    @ideatag = IdeaTag.new(:tag_id => :t_id, :idea_id => :i_id)
    @ideatag.save
  end
  
  def destroy
    idea = Idea.find(params[:i_id])
    tag = Tag.find(params[:t_id])
    
    idea_tag = IdeaTag.find_by_idea_id_and_tag_id(idea.id, tag.id)
    idea_tag.destroy
    
    redirect_to idea
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end
  
  def show
    @idea = Idea.find(params[:id])
    @comments = Comment.find_all_by_idea_id(@idea.id) 
    @comment = Comment.new
    @tags = Tag.all
    @idea_tags = @idea.tags
    #@idea_tags = Idea_Tag.find_all_by_idea_id(@idea.id)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end
  
  def new
    @idea = Idea.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end
  
  def create
    @idea = Idea.new(params[:idea])
    
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def upvote
    @idea = Idea.find(params[:id])
    @ideas = Idea.all
    
    if @idea.votes != nil
      @idea.votes += 1
    else
      @idea.votes = 1
    end
    @idea.save
    
    redirect_to ideas_path
  end
  
  def select_tag
    tags = Tag.find(params[:tag_id]) #this is an array of all the tags they selected in the multi-select
    idea = Idea.find(params[:idea_id])
    
    tags.each do |tag|
      tag_exists = false
      ideatags = IdeaTag.find_all_by_idea_id(idea.id)
      
      ideatags.each do |ideatag|
        if ideatag.tag_id == tag.id
          tag_exists = true
        end
      end
      
      if tag_exists == false
        idea.tags << tag
      end
    end
    redirect_to idea
  end
  
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    
    respond_to do |format|
      format.html { redirect_to ideas_path }
      format.json { head :no_content }
    end
  end
  
  # def deselect_tag
  #   #@idea = Idea.find(params[:id])
  #   idea = Idea.find(params[:i_id])
  #   tag = Tag.find(params[:t_id])
  #   
  #   idea.tags.find(tag.id).destroy
  #   
  #   redirect_to idea
  # end
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
  
  def show
    @tag = Tag.find(params[:id])
    @ideas = @tag.ideas
  end
  
  def new
    @tag = Tag.new
  end
  
  def create
    @tag = Tag.new(params[:tag])
    
    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
  
end

app/views/comments/_form.html.erb
<%= form_for([@idea, @comment]) do |f| %>
	Comment: <%= f.text_field :text %>
	Revenue Opportunity: <%= f.number_field :revenue_opp %>
	<%= f.submit %>
<% end %>

app/views/comments/index.html.erb
Comments#index for this idea

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
comments#show

app/views/ideas/_form.html.erb
This is the ideas#new form
<%= form_for(@idea) do |f| %>
	Name: <%= f.text_field :name %>
	Description: <%= f.text_field :description %>
	<%= f.submit %>
<% end %>

app/views/ideas/index.html.erb
<ul>
<% @ideas.each do |idea| %>
	<li>
		Idea: <%= link_to idea.name, idea_path(idea.id) %>
		<br/>
		Description: <%= idea.description %>
		<br/>
		Tags: 
		<% idea.tags.each_with_index do |tag, index| %> 
			<%= tag.name %>
			<% if index != idea.tags.count - 1 %>
			|
			<% end %>
		<% end %>
		<br/>
		Votes: <%= idea.votes %> <%= link_to 'Upvote', upvote_idea_path(idea.id) %>
		<br/>
		<%= link_to "Delete Idea", idea_path(idea.id), :method => :delete, :confirm => 'Are you sure?' %>
	</li>
<% end %>
</ul>

<%= link_to 'Submit new idea', new_idea_path %>

app/views/ideas/new.html.erb
<%= render 'form' %>

app/views/ideas/show.html.erb
Idea: <%= @idea.name %>
<br/>
Votes: <%= @idea.votes %>
<br/>
Description: <%= @idea.description %>
<ul>
<% @comments.each do |comment| %>
	<li>
		Comment: <%= comment.text %>
		<br/>
		Revenue Opportunity: <%= comment.revenue_opp %>
		<br/>
	</li>
<% end %>
</ul>

<%#= link_to 'Add Comment', new_idea_comment_path(@idea.id) %>

<%= form_for([@idea, @comment]) do |f| %>
	Comment: <%= f.text_field :text %>
	<br/>
	Revenue Opportunity: <%= f.number_field :revenue_opp %>
	<br/>
	<%= f.submit %>
<% end %>

<ul>
	<% @idea_tags.each do |tag| %>
		<li>
			<%= tag.name %> <%= link_to 'Delete', idea_tag_path({:t_id => tag.id, :i_id => @idea.id}), :method => :delete %>
		</li>
	<% end %>
</ul>

<%= form_tag(select_tag_idea_path) do %>
	<%= hidden_field_tag 'idea_id', @idea.id %>
	<%= select_tag 'tag_id', options_from_collection_for_select(@tags, "id", "name"), :multiple => true %>
	<%= submit_tag "Tag this idea" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Featuremgmt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/tags/index.html.erb
<ul>
<% @tags.each do |tag| %>
	<li>
		<%= link_to tag.name, tag_path(tag) %> (<%= tag.ideas.count %> <%= "idea".pluralize(tag.ideas.count) %>)
	</li>
<% end %>
</ul>

app/views/tags/new.html.erb
<%= render 'form' %>

app/views/tags/show.html.erb
Ideas tagged as <%= @tag.name %>
<ul>
	<% @ideas.each do |idea| %>
		<li>
			<%= link_to idea.name, idea_path(idea) %>
		</li>
	<% end %>
</ul>